FROM maven:3.9.6-eclipse-temurin-21-alpine AS builder
WORKDIR /usr/spring-app/build
# RUN mvn dependency:purge-local-repository
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY layers.xml .
RUN mvn clean install -DskipTests
COPY src ./src

FROM eclipse-temurin:21.0.2_13-jre-alpine AS layers
WORKDIR /usr/spring-app/layer
COPY --from=builder /usr/spring-app/build/target/spring-boot-practice-0.0.1-SNAPSHOT.jar spring-app.jar
RUN java -Djarmode=layertools -jar spring-app.jar extract

FROM eclipse-temurin:21.0.2_13-jre-alpine
LABEL authors="regasNikolas"
WORKDIR /opt/spring-app
RUN addgroup --system appuser && adduser -S -s /usr/sbin/nologin -G appuser appuser
COPY --from=layers /usr/spring-app/layer/dependencies/ ./
COPY --from=layers /usr/spring-app/layer/spring-boot-loader/ ./
COPY --from=layers /usr/spring-app/layer/snapshot-dependencies/ ./
COPY --from=layers /usr/spring-app/layer/application/ ./
RUN chown -R appuser:appuser /opt/spring-app
USER appuser	
HEALTHCHECK --interval=30s --timeout=3s --retries=1 CMD wget -qO- http://localhost:8080/actuator/health/ | grep UP || exit 1
EXPOSE 8080
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]